

// 불러올 때 이미지 사이즈 할당 가능 ex : svgs.react('32px')

const svgs = {
    aftereffects: (size) => <img src={`${process.env.PUBLIC_URL}/svg/aftereffects-original.svg`} alt="After Effects" style={{ width: size || '16px', height: size || '16px' }} />,
    amazonwebservices: (size) => <img src={`${process.env.PUBLIC_URL}/svg/amazonwebservices-original.svg`} alt="Amazon Web Services" style={{ width: size || '16px', height: size || '16px' }} />,
    android: (size) => <img src={`${process.env.PUBLIC_URL}/svg/android-original.svg`} alt="Android" style={{ width: size || '16px', height: size || '16px' }} />,
    apple: (size) => <img src={`${process.env.PUBLIC_URL}/svg/apple-original.svg`} alt="Apple" style={{ width: size || '16px', height: size || '16px' }} />,
    blender: (size) => <img src={`${process.env.PUBLIC_URL}/svg/blender-original.svg`} alt="Blender" style={{ width: size || '16px', height: size || '16px' }} />,
    c: (size) => <img src={`${process.env.PUBLIC_URL}/svg/c-original.svg`} alt="C Language" style={{ width: size || '16px', height: size || '16px' }} />,
    canva: (size) => <img src={`${process.env.PUBLIC_URL}/svg/canva-original.svg`} alt="Canva" style={{ width: size || '16px', height: size || '16px' }} />,
    css3: (size) => <img src={`${process.env.PUBLIC_URL}/svg/css3-original.svg`} alt="CSS3" style={{ width: size || '16px', height: size || '16px' }} />,
    django: (size) => <img src={`${process.env.PUBLIC_URL}/svg/django-plain.svg`} alt="Django" style={{ width: size || '16px', height: size || '16px' }} />,
    express: (size) => <img src={`${process.env.PUBLIC_URL}/svg/express-original.svg`} alt="Express" style={{ width: size || '16px', height: size || '16px' }} />,
    figma: (size) => <img src={`${process.env.PUBLIC_URL}/svg/figma-original.svg`} alt="Figma" style={{ width: size || '16px', height: size || '16px' }} />,
    flutter: (size) => <img src={`${process.env.PUBLIC_URL}/svg/flutter-original.svg`} alt="Flutter" style={{ width: size || '16px', height: size || '16px' }} />,
    git: (size) => <img src={`${process.env.PUBLIC_URL}/svg/git-original.svg`} alt="Git" style={{ width: size || '16px', height: size || '16px' }} />,
    github: (size) => <img src={`${process.env.PUBLIC_URL}/svg/github-original.svg`} alt="GitHub" style={{ width: size || '16px', height: size || '16px' }} />,
    go: (size) => <img src={`${process.env.PUBLIC_URL}/svg/go-original.svg`} alt="Go" style={{ width: size || '16px', height: size || '16px' }} />,
    html5: (size) => <img src={`${process.env.PUBLIC_URL}/svg/html5-original.svg`} alt="HTML5" style={{ width: size || '16px', height: size || '16px' }} />,
    illustrator: (size) => <img src={`${process.env.PUBLIC_URL}/svg/illustrator-plain.svg`} alt="Illustrator" style={{ width: size || '16px', height: size || '16px' }} />,
    java: (size) => <img src={`${process.env.PUBLIC_URL}/svg/java-original.svg`} alt="Java" style={{ width: size || '16px', height: size || '16px' }} />,
    javascript: (size) => <img src={`${process.env.PUBLIC_URL}/svg/javascript-original.svg`} alt="JavaScript" style={{ width: size || '16px', height: size || '16px' }} />,
    jira: (size) => <img src={`${process.env.PUBLIC_URL}/svg/jira-original.svg`} alt="Jira" style={{ width: size || '16px', height: size || '16px' }} />,
    kotlin: (size) => <img src={`${process.env.PUBLIC_URL}/svg/kotlin-original.svg`} alt="Kotlin" style={{ width: size || '16px', height: size || '16px' }} />,
    kubernetes: (size) => <img src={`${process.env.PUBLIC_URL}/svg/kubernetes-plain.svg`} alt="Kubernetes" style={{ width: size || '16px', height: size || '16px' }} />,
    mongodb: (size) => <img src={`${process.env.PUBLIC_URL}/svg/mongodb-original.svg`} alt="MongoDB" style={{ width: size || '16px', height: size || '16px' }} />,
    mysql: (size) => <img src={`${process.env.PUBLIC_URL}/svg/mysql-original.svg`} alt="MySQL" style={{ width: size || '16px', height: size || '16px' }} />,
    nestjs: (size) => <img src={`${process.env.PUBLIC_URL}/svg/nestjs-plain.svg`} alt="NestJS" style={{ width: size || '16px', height: size || '16px' }} />,
    nextjs: (size) => <img src={`${process.env.PUBLIC_URL}/svg/nextjs-original.svg`} alt="Next.js" style={{ width: size || '16px', height: size || '16px' }} />,
    nodejs: (size) => <img src={`${process.env.PUBLIC_URL}/svg/nodejs-original.svg`} alt="Node.js" style={{ width: size || '16px', height: size || '16px' }} />,
    notion: (size) => <img src={`${process.env.PUBLIC_URL}/svg/notion-original.svg`} alt="Notion" style={{ width: size || '16px', height: size || '16px' }} />,
    nuxtjs: (size) => <img src={`${process.env.PUBLIC_URL}/svg/nuxtjs-original.svg`} alt="Nuxt.js" style={{ width: size || '16px', height: size || '16px' }} />,
    oracle: (size) => <img src={`${process.env.PUBLIC_URL}/svg/oracle-original.svg`} alt="Oracle" style={{ width: size || '16px', height: size || '16px' }} />,
    photoshop: (size) => <img src={`${process.env.PUBLIC_URL}/svg/photoshop-plain.svg`} alt="Photoshop" style={{ width: size || '16px', height: size || '16px' }} />,
    postgresql: (size) => <img src={`${process.env.PUBLIC_URL}/svg/postgresql-original.svg`} alt="PostgreSQL" style={{ width: size || '16px', height: size || '16px' }} />,
    react: (size) => <img src={`${process.env.PUBLIC_URL}/svg/react-original.svg`} alt="React" style={{ width: size || '16px', height: size || '16px' }} />,
    reactnative: (size) => <img src={`${process.env.PUBLIC_URL}/svg/reactnative.png`} alt="React Native" style={{ width: size || '16px', height: size || '16px' }} />,
    rust: (size) => <img src={`${process.env.PUBLIC_URL}/svg/rust-plain.svg`} alt="Rust" style={{ width: size || '16px', height: size || '16px' }} />,
    slack: (size) => <img src={`${process.env.PUBLIC_URL}/svg/slack-original.svg`} alt="Slack" style={{ width: size || '16px', height: size || '16px' }} />,
    spring: (size) => <img src={`${process.env.PUBLIC_URL}/svg/spring-original.svg`} alt="Spring" style={{ width: size || '16px', height: size || '16px' }} />,
    svelte: (size) => <img src={`${process.env.PUBLIC_URL}/svg/svelte-original.svg`} alt="Svelte" style={{ width: size || '16px', height: size || '16px' }} />,
    swift: (size) => <img src={`${process.env.PUBLIC_URL}/svg/swift-original.svg`} alt="Swift" style={{ width: size || '16px', height: size || '16px' }} />,
    tailwindcss: (size) => <img src={`${process.env.PUBLIC_URL}/svg/tailwindcss-plain.svg`} alt="Tailwind CSS" style={{ width: size || '16px', height: size || '16px' }} />,
    trello: (size) => <img src={`${process.env.PUBLIC_URL}/svg/trello-original.svg`} alt="Trello" style={{ width: size || '16px', height: size || '16px' }} />,
    typescript: (size) => <img src={`${process.env.PUBLIC_URL}/svg/typescript-original.svg`} alt="TypeScript" style={{ width: size || '16px', height: size || '16px' }} />,
    vuejs: (size) => <img src={`${process.env.PUBLIC_URL}/svg/vuejs-original.svg`} alt="Vue.js" style={{ width: size || '16px', height: size || '16px' }} />,
    velog: (size) => <img src={`${process.env.PUBLIC_URL}/svg/velog-original.svg`} alt="Velog" style={{ width: size || '16px', height: size || '16px' }} />,
    webpack: (size) => <img src={`${process.env.PUBLIC_URL}/svg/webpack-original.svg`} alt="Webpack" style={{ width: size || '16px', height: size || '16px' }} />,
    windows: (size) => <img src={`${process.env.PUBLIC_URL}/svg/windows-plain.svg`} alt="Windows" style={{ width: size || '16px', height: size || '16px' }} />,
};

export default svgs;