
const svgs = {
    aftereffects: <img src={`${process.env.PUBLIC_URL}/svg/aftereffects-original.svg`} alt="After Effects" />,
    amazonwebservices: <img src={`${process.env.PUBLIC_URL}/svg/amazonwebservices-original.svg`} alt="Amazon Web Services" />,
    android: <img src={`${process.env.PUBLIC_URL}/svg/android-original.svg`} alt="Android" />,
    apple: <img src={`${process.env.PUBLIC_URL}/svg/apple-original.svg`} alt="Apple" />,
    blender: <img src={`${process.env.PUBLIC_URL}/svg/blender-original.svg`} alt="Blender" />,
    c: <img src={`${process.env.PUBLIC_URL}/svg/c-original.svg`} alt="C Language" />,
    canva: <img src={`${process.env.PUBLIC_URL}/svg/canva-original.svg`} alt="Canva" />,
    css3: <img src={`${process.env.PUBLIC_URL}/svg/css3-original.svg`} alt="CSS3" />,
    django: <img src={`${process.env.PUBLIC_URL}/svg/django-plain.svg`} alt="Django" />,
    express: <img src={`${process.env.PUBLIC_URL}/svg/express-original.svg`} alt="Express" />,
    figma: <img src={`${process.env.PUBLIC_URL}/svg/figma-original.svg`} alt="Figma" />,
    flutter: <img src={`${process.env.PUBLIC_URL}/svg/flutter-original.svg`} alt="Flutter" />,
    git: <img src={`${process.env.PUBLIC_URL}/svg/git-original.svg`} alt="Git" />,
    github: <img src={`${process.env.PUBLIC_URL}/svg/github-original.svg`} alt="GitHub" />,
    go: <img src={`${process.env.PUBLIC_URL}/svg/go-original.svg`} alt="Go" />,
    html5: <img src={`${process.env.PUBLIC_URL}/svg/html5-original.svg`} alt="HTML5" />,
    illustrator: <img src={`${process.env.PUBLIC_URL}/svg/illustrator-plain.svg`} alt="Illustrator" />,
    java: <img src={`${process.env.PUBLIC_URL}/svg/java-original.svg`} alt="Java" />,
    javascript: <img src={`${process.env.PUBLIC_URL}/svg/javascript-original.svg`} alt="JavaScript" />,
    jira: <img src={`${process.env.PUBLIC_URL}/svg/jira-original.svg`} alt="Jira" />,
    kotlin: <img src={`${process.env.PUBLIC_URL}/svg/kotlin-original.svg`} alt="Kotlin" />,
    kubernetes: <img src={`${process.env.PUBLIC_URL}/svg/kubernetes-plain.svg`} alt="Kubernetes" />,
    mongodb: <img src={`${process.env.PUBLIC_URL}/svg/mongodb-original.svg`} alt="MongoDB" />,
    mysql: <img src={`${process.env.PUBLIC_URL}/svg/mysql-original.svg`} alt="MySQL" />,
    nestjs: <img src={`${process.env.PUBLIC_URL}/svg/nestjs-plain.svg`} alt="NestJS" />,
    nextjs: <img src={`${process.env.PUBLIC_URL}/svg/nextjs-original.svg`} alt="Next.js" />,
    nodejs: <img src={`${process.env.PUBLIC_URL}/svg/nodejs-original.svg`} alt="Node.js" />,
    notion: <img src={`${process.env.PUBLIC_URL}/svg/notion-original.svg`} alt="Notion" />,
    nuxtjs: <img src={`${process.env.PUBLIC_URL}/svg/nuxtjs-original.svg`} alt="Nuxt.js" />,
    oracle: <img src={`${process.env.PUBLIC_URL}/svg/oracle-original.svg`} alt="Oracle" />,
    photoshop: <img src={`${process.env.PUBLIC_URL}/svg/photoshop-plain.svg`} alt="Photoshop" />,
    postgresql: <img src={`${process.env.PUBLIC_URL}/svg/postgresql-original.svg`} alt="PostgreSQL" />,
    react: <img src={`${process.env.PUBLIC_URL}/svg/react-original.svg`} alt="React" />,
    reactnative: <img src={`${process.env.PUBLIC_URL}/svg/reactnative.png`} alt="React Native" />,
    rust: <img src={`${process.env.PUBLIC_URL}/svg/rust-plain.svg`} alt="Rust" />,
    slack: <img src={`${process.env.PUBLIC_URL}/svg/slack-original.svg`} alt="Slack" />,
    spring: <img src={`${process.env.PUBLIC_URL}/svg/spring-original.svg`} alt="Spring" />,
    svelte: <img src={`${process.env.PUBLIC_URL}/svg/svelte-original.svg`} alt="Svelte" />,
    swift: <img src={`${process.env.PUBLIC_URL}/svg/swift-original.svg`} alt="Swift" />,
    tailwindcss: <img src={`${process.env.PUBLIC_URL}/svg/tailwindcss-plain.svg`} alt="Tailwind CSS" />,
    trello: <img src={`${process.env.PUBLIC_URL}/svg/trello-original.svg`} alt="Trello" />,
    typescript: <img src={`${process.env.PUBLIC_URL}/svg/typescript-original.svg`} alt="TypeScript" />,
    unity: <img src={`${process.env.PUBLIC_URL}/svg/unity-original.svg`} alt="Unity" />,
    vuejs: <img src={`${process.env.PUBLIC_URL}/svg/vuejs-original.svg`} alt="Vue.js" />,
};

export default svgs;
